cc_test(
    name = "fifty-fifty-test",
    srcs = ["test_fifty_fifty.cc"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        "@gtest//:main",
        "@//abc132/lib:fifty_fifty"
    ],
)
